import "./styles/reset.scss"
// import "./styles/theme/light-material.scss"
import "./styles/theme/dark-material.scss"
import "./styles/adoptor/matrial-design.scss"
import "./styles/adoptor/g-components.scss"
import "./components/components"
import "./md-v2/md-v2"
import "./widgets"
import "@material/web/ripple/ripple"

// examples
// import "./components/Loader/Loader.example"
// import "./components/Drawer/Drawer.example"
// import "./components/JsonEdit/JsonEdit.example"
// import "./components/Editor/Editor.example"
// import "./components/Tabs/Tab.example"
// import "./components/Menu/Menu.example"
// import "./components/MenuJson/MenuJson.example"
// import "./components/Modal/Modal.example"
// import "./components/MuiTab/MuiTab.example"
// import "./components/Sample/Sample.example"
// import "./components/Sidebar/Sidebar.example"

// import "./widgets/FormBuilder/FormBuilder.example"
// import "./widgets/Row/Row.example"
// import "./widgets/Circle/Circle.example"
// import "./widgets/Gauge/Gauge.example"
// import "./widgets/MyComponent/MyComponent.example"
// import "./widgets/RefrigeratorContent/RefrigeratorContent.example"
// import "./widgets/RefrigeratorFrame/RefrigeratorFrame.example"
// import "./widgets/Slider/Slider.example"
// import "./widgets/Window/Window.example"
import "./widgets/SvgContainer/SvgContainer.example"
// import "./widgets/EditBox/EditBox.example"

// import "./md-v2/Button/Button.example"
